# Generated by Django 2.2.10 on 2020-03-01 19:11

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NdviMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nri_image', models.FileField(upload_to=core.models.ndvi_image_path)),
                ('ndvi_image', models.FileField(null=True, upload_to=core.models.ndvi_image_path)),
                ('health_map', models.FileField(null=True, upload_to=core.models.ndvi_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'default_related_name': 'ndvi_maps',
            },
        ),
    ]
