# Generated by Django 2.2.10 on 2020-03-02 08:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvimap',
            name='ndvi_image',
            field=models.ImageField(null=True, upload_to=core.models.ndvi_image_path),
        ),
    ]
