# Generated by Django 2.2.10 on 2020-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0002_auto_20200302_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvimap',
            name='month',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
    ]
