# Generated by Django 2.2.10 on 2020-03-02 16:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0003_ndvimap_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvimap',
            name='health_map',
            field=models.ImageField(null=True, upload_to=core.models.ndvi_image_path),
        ),
        migrations.AlterField(
            model_name='ndvimap',
            name='nri_image',
            field=models.ImageField(upload_to=core.models.ndvi_image_path),
        ),
    ]
