# Generated by Django 2.2.10 on 2020-05-24 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0004_auto_20200302_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('air_moisture', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('soil_temperature', models.FloatField()),
                ('pole_no', models.PositiveSmallIntegerField()),
            ],
            options={
                'default_related_name': 'readings',
            },
        ),
    ]
