# Generated by Django 2.2.10 on 2020-05-30 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0005_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('nh3', models.FloatField()),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('c3h8', models.FloatField()),
                ('c4h10', models.FloatField()),
                ('ch4', models.FloatField()),
                ('h2', models.FloatField()),
                ('c2h5oh', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pole_no', models.PositiveSmallIntegerField()),
            ],
            options={
                'default_related_name': 'air_readings',
            },
        ),
    ]
