# Generated by Django 2.2.10 on 2020-06-07 21:15

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0006_airreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(unique=True)),
                ('file_preprocessed', models.ImageField(upload_to=core.models.upload_file)),
                ('file', models.FileField(upload_to=core.models.upload_file)),
            ],
            options={
                'default_related_name': 'satellite_images',
            },
        ),
    ]
