# Generated by Django 2.2.10 on 2020-06-07 21:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0007_satelliteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_file),
        ),
    ]
