# Generated by Django 2.2.19 on 2021-03-25 21:52

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0009_auto_20210311_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvimap',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ndvimap',
            name='health_map',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ndvi_image_path),
        ),
        migrations.AlterField(
            model_name='ndvimap',
            name='ndvi_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ndvi_image_path),
        ),
    ]
