# Generated by Django 2.2.19 on 2021-03-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crohmi', '0010_auto_20210325_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvimap',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
