# Generated by Django 2.2.10 on 2020-04-22 03:42

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lab_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to=core.models.upload_file)),
                ('description', models.TextField()),
            ],
            options={
                'default_related_name': 'projects',
            },
        ),
    ]
